rolling_window: 2000   # 指定rolling_window窗口大小
freq: 15m    # 指定数据频率

sym: ETHUSDT    # 指定gplearn做训练的品种数据, 不支持截面上的多品种   btcusdt ethusdt bnbusdt solusdt
y_train_ret_period: 5    # 指定在训练集上的y值是未来第几个bar的收益率差
start_date_train: '2024-08'
end_date_train: '2025-01'
start_date_test: '2025-03'
end_date_test: '2025-06'
timeframe: '15m'
data_dir: '/Volumes/Ext-Disk/data/futures/um/monthly/klines/ETHUSDT/15m'
read_frequency: 'monthly'

# ===== 可选：直接指定数据文件路径 =====
# file_path: tick交易数据文件路径（用于 data_source=micro 时）
#   - 如果指定，会优先使用此文件，忽略 daily_data_template / monthly_data_template
# kline_file_path: K线数据文件路径（用于 data_source=kline，或 micro 模式下无tick数据时的备用）
#   - 如果指定，会优先使用此文件，忽略 data_dir、start_date、end_date 等参数
# 
# 使用场景：当数据已经合并为单个文件时，可以直接指定路径，更快速便捷
# 示例（tick数据）：
# file_path: '/Volumes/Ext-Disk/data/futures/um/monthly/trades/ETHUSDT/ETHUSDT-trades-2025-01-03-merged.feather'
# 示例（K线数据）：
# kline_file_path: '/Volumes/Ext-Disk/data/combined/BTCUSDT_2025_1h.feather'

execution_mode: 'once'   # 'once' or 'loop' , 设定执行模式，once是一次性执行，loop是无限次执行

# file_path: '/Volumes/Ext-Disk/data/futures/um/ETHUSDT/bars_with_features-2025-01-01-2025-01-20-1h.feather'

gp_settings:
  population_size: 20000
  hall_of_fame: 10000
  n_components: 5000
  generations: 3
  tournament_size: 888
  const_range: null
  init_depth: [2, 5]
  metric: 'sharpe_fixed_threshold'  #'avg_pic', 'avg_sic', 'sharp', 'calmar', 'sharpe_fixed_threshold', 'sharpe_std_threshold'
  parsimony_coefficient: 0.0005    #0.0005
  p_crossover: 0.8
  p_subtree_mutation: 0.02
  p_hoist_mutation: 0.02
  p_point_mutation: 0.02
  p_point_replace: 0.5
  corrcoef_threshold: 0.8
  n_jobs: -1



# ===== 微结构数据源与特征家族控制（新增） =====
# 数据源：kline（默认）/ micro（微结构）
data_source: kline

# 是否启用 features/ 下逐笔级提取器（建议 true，有交易逐笔数据时）
use_feature_extractors: true
trades_dir: '/path/to/trades'   # 放逐笔数据的目录（需自备 {SYM}_trades.feather/csv）
trades_load_mode: daily            # 或 daily/monthly
prefer_trades_feather: true
daily_data_template: '/Volumes/Ext-Disk/data/futures/um/daily/trades/ETHUSDT/ETHUSDT-trades-{date}.feather'       # 或 .zip
monthly_data_template: '/Volumes/Ext-Disk/data/futures/um/monthly/trades/ETHUSDT/ETHUSDT-trades-{month}.feather'  # 或 .zip
bar_builder: time                 # 或 dollar
dollar_threshold: 1000000
feature_window_bars: 48

feature_types: ['orderflow']


# 仅挖某一“特征家族”（单选），可选：
# momentum | liquidity | orderflow | tail | bucketed_flow
active_family: tail

# 或者用关键词筛选（二选一：与 active_family 互斥，留空即可）
# include 命中的才保留；exclude 命中的会删除
# feature_family_include: ['impact_', 'amihud', 'kyle', 'cs_spread']   # 例如流动性/冲击
# feature_family_exclude: ['large_', 'tail_']   